
language: python
python:
# - "3.3"
# - "3.4"
 - "3.5"
 - "nightly" # currently points to 3.6-dev

services:
 - mongodb

install:
 - "pip install pymongo"
 - "python setup.py install"

script:
 - "nosetests -v --with-coverage"

after_success:
 - "bash <(curl -s https://codecov.io/bash)"
