
language: python
python:
# - "3.3"
# - "3.4"
 - "3.5"
 - "nightly" # currently points to 3.6-dev

services:
 - mongodb

before_install:
 - "pip install coverage"
 - "pip install mypy-lang==0.4.4"

install:
 - "pip install pymongo"
 - "python setup.py install"

script:
 - "nosetests -v --with-coverage --cover-package='aw_core,aw_datastore'"
 # Forgiving checking
 - "export MYPYPATH=$TRAVIS_BUILD_DIR/stubs"
 - "mypy aw_core --silent-imports"
 - "mypy aw_datastore --silent-imports"

 # The following typechecking won't fail the build
 # Don't silence missing imports
 - "mypy aw_core; exit 0"
 - "mypy aw_datastore; exit 0"
 # Strict checking
 - "mypy --check-untyped-defs --disallow-untyped-defs aw_core; exit 0"
 # Super strict checking
 - "mypy --check-untyped-defs --disallow-untyped-defs --disallow-untyped-calls aw_core; exit 0"

after_success:
 - "bash <(curl -s https://codecov.io/bash)"
